# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.provision "docker"
    config.vm.provision "shell", inline:
        "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

    # Add shared folder
    config.vm.synced_folder "../", "/app"
    # Add private network
    # Add port forwarding
    config.vm.network "forwarded_port", guest: 80, host: 1234
end
